plugins:
  - jekyll-environment-variables
logo:
  mobile: images/logo/logo-mobile.svg
  mobile_height: 32px
  mobile_width: 32px
  desktop: images/logo/logo.svg
  desktop_height: 32px
  desktop_width: 120px
permalink: pretty
sass:
  style: compressed
url: url
defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: team
    values:
      layout: team
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
title: hello there
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
baseurl: /
description: test de
footer:
  copyright_text: copy
home:
  limit_services: 6
